#%RAML 0.8
---
title: AQS API
version: 1.0
baseUri: http://localhost:8081/api
/sites:
  get:
    description: Active AQS by longitude & latitude
    queryParameters:
      longitude:
        displayName: longitude
        type: number
        description: longitude
        example: -122.0841964
        required: true
      latitude:
        displayName: latitude
        type: number
        description: latitude
        example: 37.4223607
        required: true
    responses:
      200:
        body: 
         application/json:
          example: !include get_sites_response_example.json
          schema: !include get_sites_response_schema.json
        description: Get list of sites around the requested long/lat.
      400:
        description: !include response_400.txt
      500:
        description: !include response_500.txt
      503:
        description:  !include response_503.txt