CREATE TABLE `sites` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `State Code` varchar(45) DEFAULT NULL,
  `County Code` varchar(45) DEFAULT NULL,
  `Site Number` varchar(45) DEFAULT NULL,
  `Latitude` decimal(9,6) DEFAULT NULL,
  `Longitude` decimal(9,6) DEFAULT NULL,
  `Datum` varchar(45) DEFAULT NULL,
  `Elevation` varchar(45) DEFAULT NULL,
  `Land Use` varchar(45) DEFAULT NULL,
  `Location Setting` varchar(45) DEFAULT NULL,
  `Site Established Date` varchar(45) DEFAULT NULL,
  `Site Closed Date` varchar(45) DEFAULT NULL,
  `Met Site State Code` varchar(45) DEFAULT NULL,
  `Met Site County Code` varchar(45) DEFAULT NULL,
  `Met Site Site Number` varchar(45) DEFAULT NULL,
  `Met Site Type` varchar(45) DEFAULT NULL,
  `Met Site Distance` varchar(45) DEFAULT NULL,
  `Met Site Direction` varchar(45) DEFAULT NULL,
  `GMT Offset` varchar(45) DEFAULT NULL,
  `Owning Agency` varchar(145) DEFAULT NULL,
  `Local Site Name` varchar(145) DEFAULT NULL,
  `Address` varchar(145) DEFAULT NULL,
  `Zip Code` varchar(45) DEFAULT NULL,
  `State Name` varchar(45) DEFAULT NULL,
  `County Name` varchar(45) DEFAULT NULL,
  `City Name` varchar(145) DEFAULT NULL,
  `CBSA Name` varchar(145) DEFAULT NULL,
  `Tribe Name` varchar(145) DEFAULT NULL,
  `Extraction Date` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
