%dw 1.0
%output application/java
---
[
  {
    "Site Established Date": "1/1/59",
    "State Code": "45",
    "Address": "900 CLEMSON ROAD [Sandhill]",
    "Met Site State Code": "",
    "County Name": "Richland",
    "Elevation": "139",
    "Local Site Name": "SANDHILL EXPERIMENTAL STATION",
    "Longitude": -80.868318,
    "Tribe Name": "",
    "Owning Agency": "South Carolina Department Health And Environmental Control",
    "Met Site Type": "ON-SITE MET EQUIP",
    "Met Site Direction": "",
    "Met Site County Code": "",
    "Extraction Date": "12/2/15",
    "Zip Code": "29229",
    "Met Site Site Number": "",
    "State Name": "South Carolina",
    "Site Closed Date": "",
    "Location Setting": "RURAL",
    "CBSA Name": "Columbia, SC",
    "Site Number": "1001",
    "Met Site Distance": "",
    "GMT Offset": "-5",
    "Datum": "WGS84",
    "Land Use": "AGRICULTURAL",
    "Latitude": 34.131262,
    "City Name": "Not in a City",
    "County Code": "79"
  },
  {
    "Site Established Date": "1/1/87",
    "State Code": "45",
    "Address": "8231 PARKLANE ROAD [Hayne Lab]",
    "Met Site State Code": "45",
    "County Name": "Richland",
    "Elevation": "98",
    "Local Site Name": "HAYNE BLDG - DAQA LAB - THIRD FLOOR",
    "Longitude": -80.96167,
    "Tribe Name": "",
    "Owning Agency": "South Carolina Department Health And Environmental Control",
    "Met Site Type": "OTHER AIRS SITE",
    "Met Site Direction": "ENE",
    "Met Site County Code": "79",
    "Extraction Date": "12/2/15",
    "Zip Code": "29223",
    "Met Site Site Number": "1001",
    "State Name": "South Carolina",
    "Site Closed Date": "",
    "Location Setting": "SUBURBAN",
    "CBSA Name": "Columbia, SC",
    "Site Number": "9007",
    "Met Site Distance": "9600",
    "GMT Offset": "-5",
    "Datum": "WGS84",
    "Land Use": "RESIDENTIAL",
    "Latitude": 34.091028,
    "City Name": "Dentsville (Dents)",
    "County Code": "79"
  }
 ]